import 'package:flutter/material.dart';import 'package:quran_story_game/core/app_export.dart';import 'package:quran_story_game/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:quran_story_game/widgets/app_bar/custom_app_bar.dart';import 'package:quran_story_game/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';import 'package:quran_story_game/presentation/test_page_eleven_dialog/test_page_eleven_dialog.dart';class TestPageTwelveScreen extends StatelessWidget {const TestPageTwelveScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(left: 41.h, top: 65.v, right: 41.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 48.v, width: 187.h, text: "اختبر معلوماتك عن القصة ", margin: EdgeInsets.only(left: 44.h), buttonStyle: CustomButtonStyles.fillDeepOrange, buttonTextStyle: CustomTextStyles.titleSmallBluegray800), SizedBox(height: 45.v), SizedBox(height: 285.v, width: 292.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.bottomRight, child: Container(height: 268.v, width: 275.h, decoration: BoxDecoration(color: appTheme.blueGray100.withOpacity(0.47), borderRadius: BorderRadius.circular(10.h), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.1), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(5, 5))]))), _buildSeventeen(context)])), SizedBox(height: 5.v)])), bottomNavigationBar: _buildCheckAnswer(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 66.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 24.h, top: 7.v, bottom: 7.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: SizedBox(height: 8.v, child: AnimatedSmoothIndicator(activeIndex: 0, count: 6, effect: ScrollingDotsEffect(spacing: 2, activeDotColor: appTheme.gray30004, dotColor: appTheme.lightBlueA700, dotHeight: 8.v, dotWidth: 34.h)))); } 
/// Section Widget
Widget _buildSeventeen(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 278.v, width: 282.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 268.v, width: 275.h, decoration: BoxDecoration(color: appTheme.blueGray100.withOpacity(0.47), borderRadius: BorderRadius.circular(10.h), boxShadow: [BoxShadow(color: appTheme.black900.withOpacity(0.1), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(5, 5))]))), Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 16.v), decoration: AppDecoration.outlineBlack.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(width: 197.h, margin: EdgeInsets.only(left: 17.h, right: 15.h), child: Text("من هو الذي كوّن جيش لهدم الكعبة :", maxLines: null, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeTajawalBlack900Bold.copyWith(height: 2.15))), SizedBox(height: 17.v), CustomElevatedButton(text: "أبرهة الحبشي", buttonStyle: CustomButtonStyles.outlinePrimaryTL51), SizedBox(height: 16.v), CustomElevatedButton(text: "مسيلمة الكذاب", buttonStyle: CustomButtonStyles.outlinePrimaryTL51), SizedBox(height: 15.v), CustomElevatedButton(text: "أبو جهل", buttonStyle: CustomButtonStyles.outlinePrimaryTL51), SizedBox(height: 10.v), CustomElevatedButton(height: 48.v, width: 91.h, text: "السؤال 1 من 5", buttonStyle: CustomButtonStyles.fillLightGreen), SizedBox(height: 7.v)])))]))); } 
/// Section Widget
Widget _buildCheckAnswer(BuildContext context) { return CustomElevatedButton(width: 231.h, text: "تحقق من الإجابة", margin: EdgeInsets.only(left: 73.h, right: 71.h, bottom: 40.v), leftIcon: Container(margin: EdgeInsets.only(right: 10.h), child: CustomImageView(imagePath: ImageConstant.imgFrameArrow, height: 16.v, width: 14.h)), buttonTextStyle: theme.textTheme.bodyLarge!, onPressed: () {onTapCheckAnswer(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Displays a dialog with the [TestPageElevenDialog] content.
onTapCheckAnswer(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: TestPageElevenDialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
