import '../iphone_13_mini_fiftysix_page/widgets/gametitlelist_item_widget.dart';import 'package:flutter/material.dart';import 'package:quran_story_game/core/app_export.dart';import 'package:quran_story_game/widgets/custom_rating_bar.dart';import 'package:quran_story_game/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class Iphone13MiniFiftysixPage extends StatelessWidget {Iphone13MiniFiftysixPage({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, decoration: AppDecoration.fillSecondaryContainer, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [_buildImageStack(context), SizedBox(height: 21.v), Padding(padding: EdgeInsets.symmetric(horizontal: 29.h), child: CustomSearchView(controller: searchController, hintText: "                                                           البحث    ")), SizedBox(height: 20.v), _buildAchievementCard(context), SizedBox(height: 20.v), _buildEyeFilledRow(context), SizedBox(height: 34.v), _buildGameTitleList(context), SizedBox(height: 31.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 34.h), child: Text("بوسيطة النقل", style: CustomTextStyles.titleLargeTajawalOnPrimaryContainer))), SizedBox(height: 41.v), _buildSilhouetteScroll(context)])))))); } 
/// Section Widget
Widget _buildImageStack(BuildContext context) { return SizedBox(height: 107.v, width: double.maxFinite, child: Stack(alignment: Alignment.centerRight, children: [CustomImageView(imagePath: ImageConstant.imgImages11, height: 107.v, width: 375.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 26.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(top: 5.v, bottom: 7.v), child: Text("مرحباً محمد", style: CustomTextStyles.titleMediumMontserratPrimary)), CustomImageView(imagePath: ImageConstant.imgEllipse, height: 42.adaptSize, width: 42.adaptSize, radius: BorderRadius.circular(21.h), margin: EdgeInsets.only(left: 15.h))])))])); } 
/// Section Widget
Widget _buildAchievementCard(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 28.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Expanded(child: Padding(padding: EdgeInsets.only(bottom: 30.v), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 6.v), child: CustomRatingBar(initialRating: 0)), Padding(padding: EdgeInsets.only(top: 6.v), child: Text("مجتهد ", style: CustomTextStyles.titleSmallPrimary))]), SizedBox(height: 8.v), Align(alignment: Alignment.centerRight, child: Text("لقد أكملت هذه القصة 10 مرات.", style: CustomTextStyles.labelLargeTajawal))]))), Container(height: 66.adaptSize, width: 66.adaptSize, margin: EdgeInsets.only(left: 13.h, top: 6.v, bottom: 6.v), padding: EdgeInsets.all(3.h), decoration: AppDecoration.fillOrange.copyWith(borderRadius: BorderRadiusStyle.roundedBorder35), child: CustomImageView(imagePath: ImageConstant.imgImage41, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h), alignment: Alignment.center))])); } 
/// Section Widget
Widget _buildEyeFilledRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 36.h, right: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Opacity(opacity: 0.7, child: CustomImageView(imagePath: ImageConstant.imgAntDesignEyeFilled, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 5.v, bottom: 2.v))), Opacity(opacity: 0.7, child: Padding(padding: EdgeInsets.only(left: 8.h, top: 3.v), child: Text("78.4K Viewers", style: CustomTextStyles.bodyMediumPoppinsBlack900_2))), Spacer(), Text("خريطة القصة", style: CustomTextStyles.titleLargeTajawalOnPrimaryContainer)])); } 
/// Section Widget
Widget _buildGameTitleList(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 93.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 10.h);}, itemCount: 3, itemBuilder: (context, index) {return GametitlelistItemWidget();}))); } 
/// Section Widget
Widget _buildSilhouetteScroll(BuildContext context) { return SingleChildScrollView(scrollDirection: Axis.horizontal, child: IntrinsicWidth(child: GestureDetector(onTap: () {onTapNowLive(context);}, child: Row(children: [Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), color: appTheme.gray70056, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder16), child: Container(height: 94.v, width: 169.h, decoration: AppDecoration.fillGray70056.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgVectorSilhouet, height: 42.v, width: 34.h, radius: BorderRadius.circular(16.h), alignment: Alignment.bottomRight), Align(alignment: Alignment.bottomRight, child: Container(height: 5.v, width: 93.h, margin: EdgeInsets.only(bottom: 2.v), decoration: BoxDecoration(color: appTheme.black900.withOpacity(0.5), borderRadius: BorderRadius.circular(46.h)))), CustomImageView(imagePath: ImageConstant.imgUnnamed2, height: 81.v, width: 117.h, radius: BorderRadius.circular(16.h), alignment: Alignment.topRight, margin: EdgeInsets.only(top: 3.v, right: 18.h))]))), Container(height: 94.v, width: 349.h, margin: EdgeInsets.only(left: 10.h), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topRight, child: Padding(padding: EdgeInsets.only(top: 12.v, right: 94.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgAntDesignEyeFilledGray30002, height: 10.adaptSize, width: 10.adaptSize, margin: EdgeInsets.only(bottom: 19.v)), Container(width: 13.h, margin: EdgeInsets.only(left: 2.h), child: Text("8.1K", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray10003.copyWith(height: 1.17)))]))), Align(alignment: Alignment.center, child: SizedBox(width: 349.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [SizedBox(height: 94.v, width: 169.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 94.v, width: 169.h, decoration: BoxDecoration(color: appTheme.indigo300, borderRadius: BorderRadius.circular(16.h)))), CustomImageView(imagePath: ImageConstant.imgF3y31j6xmaalult, height: 94.v, width: 169.h, radius: BorderRadius.circular(16.h), alignment: Alignment.center)])), SizedBox(height: 94.v, width: 169.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(height: 94.v, width: 169.h, decoration: BoxDecoration(color: appTheme.indigo300, borderRadius: BorderRadius.circular(16.h)))), CustomImageView(imagePath: ImageConstant.img1, height: 94.v, width: 169.h, radius: BorderRadius.circular(16.h), alignment: Alignment.center)]))])))]))])))); } 
/// Navigates to the iphone13MiniSixtythreeScreen when the action is triggered.
onTapNowLive(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone13MiniSixtythreeScreen); } 
 }
